### ISSUE TITLE
Installation is not working

### ISSUE THREAD

**Issue by onekk** [fredcamps/lsp-jedi#13]
Hello I0ve tried to put in my init.el the code, but it seems that is not working in invoking jedi when opening a python file.

lsp-mode is working, as I0ve successfully installed a Latex server (texlab).

I have installed jedy-language server using my distro (Arch Linux), but not error message appears.

I have disable the code:

```
    (use-package lsp-jedi
      :ensure t
      :config
      (with-eval-after-load "lsp-mode"
        (add-to-list 'lsp-disabled-clients 'pyls)
        (add-to-list 'lsp-enabled-clients 'jedi)))
```

as it prevents latex to work, I suspect the line that defines "lsp-enabled-clients" are not correct.

I have managed to rework the lines as:

```
;; python completion
(require 'lsp-jedi)

(add-to-list 'lsp-enabled-clients 'jedi)

(with-eval-after-load "python-mode"
    (add-hook 'python-mode 'lsp))

;; END python completion
```

Following the same "working" code for LaTex but no luck.

I'm using:

GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4)  of 2021-03-26

from Arch Linux.

TIA and Regards

Carlo D.

**Comment by fredcamps** [comment]
did you try this?
```
(use-package lsp-jedi
      :ensure t
      :config
      (with-eval-after-load "python-mode"
        (add-to-list 'lsp-disabled-clients 'pyls)
        (add-to-list 'lsp-enabled-clients 'jedi)))
```

**Comment by onekk** [comment]
Sorry I'm not using jedi anymore, at least not directly, (I'm using pyls now)

Regards

Carlo D.
