### ISSUE TITLE
Configuration instructions

### ISSUE THREAD

**Issue by spookylukey** [fredcamps/lsp-jedi#16]
I'm lost trying to work out how to configure this.

The instructions on [jedi-language-server](https://github.com/pappasam/jedi-language-server) itself are not very helpful. They suggest using [coc-jedi](https://github.com/pappasam/coc-jedi#configuration) which appears to be a vim thing.

In particular, the bare minimum you usually need to configure at a project level is how to get jedi-language-server to find dependencies in the virtualenv you are using for a project.

Thanks!

**Comment by fredcamps** [comment]
@spookylukey to use jedi language server with virtualenv, you must install virtualenvwrapper package from MELPA

**Comment by fredcamps** [comment]
@spookylukey I've updated the README with a better solution instruction
