### ISSUE TITLE
Are move refactorings supported?

### ISSUE THREAD

**Issue by jgarte** [fredcamps/lsp-jedi#22]
Hi,

Do you happen to know if this feature is supported in this lsp-jedi package?

https://github.com/pappasam/jedi-language-server/issues/209

I'm also not sure how to use it. There are no tutorials I've seen and I haven't figured it out yet.

Any help is much appreciated.

**Comment by wyuenho** [comment]
As the linked issue has said, it just supports renaming, try `M-x lsp-rename`
