### ISSUE TITLE
After enable lsp-jedi flycheck not working

### ISSUE THREAD

**Issue by spavlovich001** [fredcamps/lsp-jedi#25]
I add to configuration

```elisp
(use-package lsp-jedi
  :ensure t)
```

And flycheck not working. If I comment this lilne - flycheck work again

**Comment by spavlovich001** [comment]
Close

**Comment by chookity-pokk** [comment]
Was this closed because you solved the problem or because it wasn't related to the package? Either way, maybe put a bit more information in your issue when you close it so when others find it they aren't left in the dark.
