### ISSUE TITLE
ValueError: `column` parameter (column_number) is not a valid range(0-1) for line line_number.

### ISSUE THREAD

**Issue by Joxos** [fredcamps/lsp-jedi#7]
![image](https://user-images.githubusercontent.com/37507136/108484703-102f4300-72d7-11eb-8565-399734b452a9.png)
Um, I get this when I'm typing some codes, and I don't know how to get rid of it. Can anyone help me?
Before it shows, everything was okay. But after it is shown, everything turns into chaos.
![image](https://user-images.githubusercontent.com/37507136/108485999-87190b80-72d8-11eb-9830-1fb26705cfda.png)
Here are all of the versions of the packages I installed:
![image](https://user-images.githubusercontent.com/37507136/108486233-d4957880-72d8-11eb-8c08-8aedcaf4834e.png)

**Comment by fredcamps** [comment]
@Joxos sorry about the late reply, probably your `jedi-language-server` installation path is not on your `PATH` environment variable, try to include this lines of code at `init.el`

```lisp
(setq lsp-jedi-executable-command "installation-path")
```
