### ISSUE TITLE
lsp-origami doesn't work

### ISSUE THREAD

**Issue by scmbradley** [fredcamps/lsp-jedi#8]
When I try to use `lsp-origami-mode` with `lsp-jedi` I get the Message:

```
lsp--send-request-async: The connected server(s) does not support method textDocument/foldingRange.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section

```

I'm not sure whether there is something wrong, or whether this issue is, in fact, a feature request...

**Comment by fredcamps** [comment]
@scmbradley Did you try to upgrade your lsp-mode package and load lsp-origami-mode before lsp-jedi?

**Comment by scmbradley** [comment]
I will experiment with this later this week and get back to you.

**Comment by fredcamps** [comment]
If this issue still on the way, feel free to re-open the issue @scmbradley

**Comment by scmbradley** [comment]
I just checked and I no longer get the error.

Folding appears to work
